name: frame_sdk
description: "The Flutter SDK for the Frame from Brilliant Labs"
version: 0.0.7
homepage: "https://github.com/OkGoDoIt/frame-sdk-flutter"
documentation: "https://docs.brilliant.xyz/frame/building-apps-sdk/#flutter"

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_blue_plus: ^1.35.3
  logging: ^1.3.0
  archive: ^4.0.3
  image: ^3.0.2
  just_audio: ^0.9.46
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: xyz.brilliant.frame_sdk
        pluginClass: FrameSdkPlugin
      ios:
        pluginClass: FrameSdkPlugin
  assets:
    - assets/frameLib.lua
